[target.thumbv7em-none-eabihf]
runner =  "probe-rs-debugger debug --chip STM32H745ZITx --speed 24000 --probe-index 0 --protocol swd --connect-under-reset  --core-index 0 --flashing-enabled --reset-after-flashing --halt-after-reset --program-binary "

rustflags = [
  "-C", "link-arg=-Tlink.x",
  # "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7em-none-eabihf" # Cortex-M4F and Cortex-M7F (with FPU)

