on:
  push:
    branches: [master, staging, trying]
  pull_request:

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ['^16']
      - run: yarn install  --frozen-lockfile
      - run: yarn vscode:prepublish
      - run: yarn probe-rs:package
