# This Action is triggered when a new release tag is created in the repository.
# Based on: https://code.visualstudio.com/api/working-with-extensions/continuous-integration#github-actions
# It packages and publishes the extension to the VSCode marketplace.

on:
  push:
    branches:
    - main
  release:
    types:
    - created

name: Publish a new patch version of the VS Code Extension
  if: success() && startsWith(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-latest'
  run: npm run probe-rs:publish
  env:
    VSCE_PAT: ${{ secrets.VS_MARKETPLACE_TOKEN }}
